name: Networks
author: Sefiraat
description: No idea yet
main: io.github.sefiraat.networks.Networks
website: https://github.com/balugaq/Networks
version: ${project.version}
api-version: 1.17
depend:
  - Slimefun
softdepend:
  - GuizhanLibPlugin
  - InfinityExpansion
  - Netheopoiesis
  - WildChests
  - mcMMO
commands:
  networks:
    description: /networks
    usage: /networks <sub>
